### ISSUE TITLE
Some firefox shortcuts don't work

### ISSUE THREAD

**Issue by And329** [Sly-Harvey/NixOS#2]
For some reason shortcuts like cntrl+w or cntrl+t don't work in firefox)

**Comment by Sly-Harvey** [comment]
@And329
> For some reason shortcuts like cntrl+w or cntrl+t don't work in firefox)

yeah so it seems. I will try to fix it, Thanks for making this issue!

**Comment by Sly-Harvey** [comment]
@And329 
> For some reason shortcuts like cntrl+w or cntrl+t don't work in firefox)

it should be fixed now. It was ui.key.accelKey in about:config with was set to 91 but i changed this value back to the default of 17 in the firefox module.

**Comment by Sly-Harvey** [comment]
@And329

    For some reason shortcuts like cntrl+w or cntrl+t don't work in firefox)

it should be fixed now. It was ui.key.accelKey in about:config with was set to 91 but i changed this value back to the default of 17 in the firefox module.

**Comment by And329** [comment]
thank you, it's fixed now)
