### ISSUE TITLE
After new update install.sh don’t work for me anymore

### ISSUE THREAD

**Issue by And329** [Sly-Harvey/NixOS#3]
What I do (step by step)
Install nixOS from usb with official installer
Chose username and password
Select London time zone 
Default uk keyboard layout
Install without any desktop environment 
Then after installation: 

nix run --experimental-features "nix-command flakes" nixpkgs#git clone https://github.com/Sly-Harvey/NixOS.git ~/NixOS

cd NixOS

sudo ./install.sh

Chose “y” when asked for hardware conf

I also have nvidia gpu (3080) and ryzen 9th gen

**Comment by Sly-Harvey** [comment]
> What I do (step by step) Install nixOS from usb with official installer Chose username and password Select London time zone Default uk keyboard layout Install without any desktop environment Then after installation:
> 
> nix run --experimental-features "nix-command flakes" nixpkgs#git clone https://github.com/Sly-Harvey/NixOS.git ~/NixOS
> 
> cd NixOS
> 
> sudo ./install.sh
> 
> Chose “y” when asked for hardware conf
> 
> I also have nvidia gpu (3080) and ryzen 9th gen

thank you for your issue! I'm currently investigating this problem, Do you have any output after the install script failed? and was the bootloader functional?

**Comment by And329** [comment]
@Sly-Harvey I fixed it by recreating my /boot partition. Btw how do i allow unfree software in your build? I'm not to familiar with flakes and can't really figure it out :(

**Comment by Sly-Harvey** [comment]
@And329 
> I fixed it by recreating my /boot partition. Btw how do i allow unfree software in your build? I'm not to familiar with flakes and can't really figure it out :(

Thats great to hear!

the NixOS wiki has a good section on this: https://nixos.wiki/wiki/Unfree_Software
ideally you want to use the per-package solution. A good example of how i implemented this is in the spicetify module. and i will also push a commit to make vscode usable in a few hours but i have to do a few things first.
