### ISSUE TITLE
Rofi launcher paths

### ISSUE THREAD

**Issue by tomaszbawor** [Sly-Harvey/NixOS#4]
Hi, I have a question, I am creating my own configuration and want to inspire (copy) from yours. I am wondering if ROFI launcher path have "custom" delibaratly, or is this something that I need to fix in my config to provide proper paths?

**Comment by Sly-Harvey** [comment]
@tomaszbawor
> Hi, I have a question, I am creating my own configuration and want to inspire (copy) from yours. I am wondering if ROFI launcher path have "custom" delibaratly, or is this something that I need to fix in my config to provide proper paths?

Sorry about the wait i have not been able to be online as much recently. As for your question I didn't do anything deliberately with ROFI but how it works is i have a hyprland keybind that launches rofi with the theme explicitly passed like this: 
$launcher = pkill rofi || rofi -show drun -modi drun,filebrowser,run,window -theme ~/.config/rofi/launchers/type-2/style-2.rasi
bind = $mainMod, A, exec, pkill -x rofi || $launcher
