### ISSUE TITLE
I can't install 

### ISSUE THREAD

**Issue by Arqiiu** [Sly-Harvey/NixOS#5]
What I do (step by step)
Install nixOS from usb with official installer
Chose disk, username, password, time zone and keyboard layout
Install without any desktop environment
Then after installation:

nix run --experimental-features "nix-command flakes" nixpkgs#git clone https://github.com/Sly-Harvey/NixOS.git ~/NixOS

nano ~/NixOS/hosts/Default/configuration.nix (to change to amd drivers)

nix-shell -p git (install.sh instantly fails without git)

cd ~/NixOS

./install.sh

This is what I get:
error: hash mismatch in fixed-output derivation '/nix/store/zxy2vva3gycdgmi5hqny6hsdc782g0cl-ms-python-python.zip.drv':
         specified: sha256-CtPOLKaTIp4uMIaGVo3h6XxP/BYilgU6GBSA5wZMW8o=
            got:    sha256-N8y0cPJeFQTsOMOD1hB/T5pZcpEMRKLfpNtMz3qdGCY=
error: 1 dependencies of derivation '/nix/store/wnb8hzaq8yvhc529nwc2q5i1wn56cxkv-vscode-extension-ms-python-python-2024.15.2024091001.drv' failed to build
error: 1 dependencies of derivation '/nix/store/65xc8i21i7v1l6030z2va0ph96mplv5m-hm_.vscodeextensions.extensionsimmutable.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1g5l5rd4yb4j417g0v21cmfh7nkkvh5s-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/95533swjcglj170iby48zzazpd175jqw-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gkg2w1gnvfy39baf867jr6mxi9rdb6dh-unit-home-manager-admin.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a4crsr1fzn0phwzfz5vfxm257lcgq0si-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kqq5fd83hwx9s3wx1v678rsdya7kkk9w-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ppyf5k1pivzdy6cn34cjmygqsvg2rapb-nixos-system-nixos-24.11.20240911.4f807e8.drv' failed to build
![Screenshot from 2024-09-25 17-27-48](https://github.com/user-attachments/assets/9cda089e-4205-429f-aa32-3c499e7805bf)
The screenshot is from GNOME but it's the same error as without any desktop environment

**Comment by Sly-Harvey** [comment]
@Arqiiu Hello there!

Yeah I am also having this problem after I installed with the latest iso.
I think it was caused by the latest iso because it was working fine on the same commit before.

Anyways I am working on a fix so hopefully I can get it fixed shortly!

**Comment by Sly-Harvey** [comment]
@Arqiiu 
> What I do (step by step) Install nixOS from usb with official installer Chose disk, username, password, time zone and keyboard layout Install without any desktop environment Then after installation:
> 
> nix run --experimental-features "nix-command flakes" nixpkgs#git clone https://github.com/Sly-Harvey/NixOS.git ~/NixOS
> 
> nano ~/NixOS/hosts/Default/configuration.nix (to change to amd drivers)
> 
> nix-shell -p git (install.sh instantly fails without git)
> 
> cd ~/NixOS
> 
> ./install.sh
> 
> This is what I get: error: hash mismatch in fixed-output derivation '/nix/store/zxy2vva3gycdgmi5hqny6hsdc782g0cl-ms-python-python.zip.drv': specified: sha256-CtPOLKaTIp4uMIaGVo3h6XxP/BYilgU6GBSA5wZMW8o= got: sha256-N8y0cPJeFQTsOMOD1hB/T5pZcpEMRKLfpNtMz3qdGCY= error: 1 dependencies of derivation '/nix/store/wnb8hzaq8yvhc529nwc2q5i1wn56cxkv-vscode-extension-ms-python-python-2024.15.2024091001.drv' failed to build error: 1 dependencies of derivation '/nix/store/65xc8i21i7v1l6030z2va0ph96mplv5m-hm_.vscodeextensions.extensionsimmutable.json.drv' failed to build error: 1 dependencies of derivation '/nix/store/1g5l5rd4yb4j417g0v21cmfh7nkkvh5s-home-manager-files.drv' failed to build error: 1 dependencies of derivation '/nix/store/95533swjcglj170iby48zzazpd175jqw-home-manager-generation.drv' failed to build error: 1 dependencies of derivation '/nix/store/gkg2w1gnvfy39baf867jr6mxi9rdb6dh-unit-home-manager-admin.service.drv' failed to build error: 1 dependencies of derivation '/nix/store/a4crsr1fzn0phwzfz5vfxm257lcgq0si-system-units.drv' failed to build error: 1 dependencies of derivation '/nix/store/kqq5fd83hwx9s3wx1v678rsdya7kkk9w-etc.drv' failed to build error: 1 dependencies of derivation '/nix/store/ppyf5k1pivzdy6cn34cjmygqsvg2rapb-nixos-system-nixos-24.11.20240911.4f807e8.drv' failed to build ![Screenshot from 2024-09-25 17-27-48](https://private-user-images.githubusercontent.com/114114291/370784365-9cda089e-4205-429f-aa32-3c499e7805bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Njk3MTEsIm5iZiI6MTcyNzQ2OTQxMSwicGF0aCI6Ii8xMTQxMTQyOTEvMzcwNzg0MzY1LTljZGEwODllLTQyMDUtNDI5Zi1hYTMyLTNjNDk5ZTc4MDViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QyMDM2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2U3YThkZmQ3YzE3YzMzOGJhNzBjZmFmMmRkNTQ3OWEzZGY4YmY4NjAwMGI4OGY3M2Y1OGM5Y2E5NGJiMWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AjeMKoz3uE80LqsUDLVgs-z3BC2gbVLZQV5NVUMDSv8) The screenshot is from GNOME but it's the same error as without any desktop environment

I've identified the problem, it was kernel version 6.11 so i downgraded to the latest stable version and now the problem is solved with the latest commit :)
simply delete your current directory of this repo and run the install script commands in the readme

**Comment by Sly-Harvey** [comment]
@Arqiiu 
> What I do (step by step) Install nixOS from usb with official installer Chose disk, username, password, time zone and keyboard layout Install without any desktop environment Then after installation:
> 
> nix run --experimental-features "nix-command flakes" nixpkgs#git clone https://github.com/Sly-Harvey/NixOS.git ~/NixOS
> 
> nano ~/NixOS/hosts/Default/configuration.nix (to change to amd drivers)
> 
> nix-shell -p git (install.sh instantly fails without git)
> 
> cd ~/NixOS
> 
> ./install.sh
> 
> This is what I get: error: hash mismatch in fixed-output derivation '/nix/store/zxy2vva3gycdgmi5hqny6hsdc782g0cl-ms-python-python.zip.drv': specified: sha256-CtPOLKaTIp4uMIaGVo3h6XxP/BYilgU6GBSA5wZMW8o= got: sha256-N8y0cPJeFQTsOMOD1hB/T5pZcpEMRKLfpNtMz3qdGCY= error: 1 dependencies of derivation '/nix/store/wnb8hzaq8yvhc529nwc2q5i1wn56cxkv-vscode-extension-ms-python-python-2024.15.2024091001.drv' failed to build error: 1 dependencies of derivation '/nix/store/65xc8i21i7v1l6030z2va0ph96mplv5m-hm_.vscodeextensions.extensionsimmutable.json.drv' failed to build error: 1 dependencies of derivation '/nix/store/1g5l5rd4yb4j417g0v21cmfh7nkkvh5s-home-manager-files.drv' failed to build error: 1 dependencies of derivation '/nix/store/95533swjcglj170iby48zzazpd175jqw-home-manager-generation.drv' failed to build error: 1 dependencies of derivation '/nix/store/gkg2w1gnvfy39baf867jr6mxi9rdb6dh-unit-home-manager-admin.service.drv' failed to build error: 1 dependencies of derivation '/nix/store/a4crsr1fzn0phwzfz5vfxm257lcgq0si-system-units.drv' failed to build error: 1 dependencies of derivation '/nix/store/kqq5fd83hwx9s3wx1v678rsdya7kkk9w-etc.drv' failed to build error: 1 dependencies of derivation '/nix/store/ppyf5k1pivzdy6cn34cjmygqsvg2rapb-nixos-system-nixos-24.11.20240911.4f807e8.drv' failed to build ![Screenshot from 2024-09-25 17-27-48](https://private-user-images.githubusercontent.com/114114291/370784365-9cda089e-4205-429f-aa32-3c499e7805bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Njk3MTEsIm5iZiI6MTcyNzQ2OTQxMSwicGF0aCI6Ii8xMTQxMTQyOTEvMzcwNzg0MzY1LTljZGEwODllLTQyMDUtNDI5Zi1hYTMyLTNjNDk5ZTc4MDViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QyMDM2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2U3YThkZmQ3YzE3YzMzOGJhNzBjZmFmMmRkNTQ3OWEzZGY4YmY4NjAwMGI4OGY3M2Y1OGM5Y2E5NGJiMWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AjeMKoz3uE80LqsUDLVgs-z3BC2gbVLZQV5NVUMDSv8) The screenshot is from GNOME but it's the same error as without any desktop environment

I've identified the problem, it was kernel version 6.11 so i downgraded to the latest stable version and now the problem is solved with the latest commit :)
simply delete your current directory of this repo and run the install script commands in the readme
